spring:
    datasource:
        url: jdbc:mysql://${DB_URL}/${DB_NAME}?useSSL=false&serverTimezone=UTC&allowPublicKeyRetrieval=true
        username: ${DB_USERNAME}
        password: ${DB_PASSWORD}
        driver-class-name: com.mysql.cj.jdbc.Driver
    jpa:
        hibernate:
            ddl-auto: update
        show-sql: true

    data:
        redis:
            host: ${REDIS_HOST}
            port: ${REDIS_PORT}
            password: ${REDIS_PASSWORD}

    mail:
        host: ${EMAIL_HOST}
        port: ${EMAIL_PORT}
        username: ${EMAIL_ADDRESS}
        password: ${EMAIL_APP_PASSWORD}
        properties:
            mail:
                smtp:
                    auth: true
                    timeout: 5000
                    starttls:
                        enable: true


jwt:
    accessSecret: ${ACCESS_SECRET}
    refreshSecret: ${REFRESH_SECRET}
    accessExp: ${ACCESS_EXP}
    refreshExp: ${REFRESH_EXP}
